// resources/js/Pages/Admin/AdminManagement/Admins/Index.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import { Link } from '@inertiajs/vue3';
import AdminShell from '@/Layouts/AdminShell.vue';
import { adminApi } from '@/lib/apiClient';

const props = defineProps({ admin: Object });
const isSuperAdmin = computed(() => props.admin?.admin_type === 'S');

const rows = ref([]);
const total = ref(0);
const page = ref(1);
const limit = ref(10);
const search = ref('');
const activeOnly = ref(false);
const loading = ref(true);
const roles = ref([]);

const view = ref('table'); // 'table' | 'create' | 'edit'
const editingId = ref(null);
const form = ref({ firstName: '', lastName: '', email: '', mobileNumber: '', password: '', adminType: 'A', roleId: '', isActive: true });
const formError = ref('');
const saving = ref(false);

const deactivateTarget = ref(null);
const passwordTarget = ref(null);
const passwordForm = ref({ new: '', confirm: '' });
const passwordError = ref('');
const copiedId = ref(null);

async function load() {
    loading.value = true;
    const res = await adminApi.getAdmins({
        page: page.value, limit: limit.value, search: search.value || undefined,
        isActive: activeOnly.value ? true : undefined,
    });
    if (res?.status !== false) {
        rows.value = res.data || [];
        total.value = res.total ?? 0;
    }
    loading.value = false;
}

async function loadRoles() {
    const res = await adminApi.getRoleDropdown();
    if (res?.status !== false) roles.value = res.data || [];
}

onMounted(() => {
    load();
    loadRoles();
});

function applySearch() {
    page.value = 1;
    load();
}

function goToPage(p) {
    page.value = p;
    load();
}

const totalPages = computed(() => Math.max(1, Math.ceil(total.value / limit.value)));

function openCreate() {
    form.value = { firstName: '', lastName: '', email: '', mobileNumber: '', password: '', adminType: 'A', roleId: '', isActive: true };
    formError.value = '';
    editingId.value = null;
    view.value = 'create';
}

function openEdit(row) {
    form.value = {
        firstName: row.first_name || '', lastName: row.last_name || '', email: row.email || '',
        mobileNumber: row.mobile_number || '', password: '', adminType: row.admin_type || 'A',
        roleId: row.role_id || '', isActive: !!row.is_active,
    };
    formError.value = '';
    editingId.value = row.admin_id;
    view.value = 'edit';
}

function cancelForm() {
    view.value = 'table';
    formError.value = '';
}

async function submitForm() {
    formError.value = '';
    saving.value = true;
    let res;
    if (editingId.value) {
        res = await adminApi.updateAdmin({
            adminId: editingId.value, firstName: form.value.firstName, lastName: form.value.lastName,
            email: form.value.email, mobileNumber: form.value.mobileNumber, adminType: form.value.adminType,
            roleId: form.value.roleId || null, isActive: form.value.isActive,
        });
    } else {
        res = await adminApi.register({
            firstName: form.value.firstName, lastName: form.value.lastName, email: form.value.email,
            mobileNumber: form.value.mobileNumber, password: form.value.password, adminType: form.value.adminType,
            roleId: form.value.roleId || null,
        });
    }
    saving.value = false;
    if (res?.status === false) {
        formError.value = res.message || 'Something went wrong.';
        return;
    }
    view.value = 'table';
    load();
}

async function toggleActive(row) {
    const next = !row.is_active;
    row.is_active = next; // optimistic
    const res = await adminApi.deleteAdmin({ adminId: row.admin_id, isActive: next });
    if (res?.status === false) {
        row.is_active = !next;
    }
}

function confirmDeactivate(row) {
    deactivateTarget.value = row;
}

async function doDeactivate() {
    const row = deactivateTarget.value;
    deactivateTarget.value = null;
    if (!row) return;
    row.is_active = false;
    await adminApi.deleteAdmin({ adminId: row.admin_id, isActive: false });
}

async function deleteRow(row) {
    if (!window.confirm(`Delete admin "${row.first_name} ${row.last_name}"?`)) return;
    await adminApi.deleteAdmin({ adminId: row.admin_id, isActive: false });
    load();
}

function openPasswordModal(row) {
    passwordTarget.value = row;
    passwordForm.value = { new: '', confirm: '' };
    passwordError.value = '';
}

async function submitPasswordReset() {
    if (passwordForm.value.new.length < 6) {
        passwordError.value = 'Password must be at least 6 characters.';
        return;
    }
    if (passwordForm.value.new !== passwordForm.value.confirm) {
        passwordError.value = 'Passwords do not match.';
        return;
    }
    const res = await adminApi.resetPassword({ adminId: passwordTarget.value.admin_id, newPassword: passwordForm.value.new });
    if (res?.status === false) {
        passwordError.value = res.message || 'Failed to reset password.';
        return;
    }
    passwordTarget.value = null;
}

function copyLoginUrl(row) {
    if (!row.login_url) return;
    navigator.clipboard?.writeText(row.login_url);
    copiedId.value = row.admin_id;
    setTimeout(() => { if (copiedId.value === row.admin_id) copiedId.value = null; }, 2000);
}
</script>

<template>
    <AdminShell title="Administrators" source="client/app/admin/admin-management/admins/page.tsx">
        <section class="rounded-lg border border-slate-200 bg-white shadow-sm">
            <div class="flex flex-col gap-3 border-b border-slate-200 p-5 lg:flex-row lg:items-center lg:justify-between">
                <div>
                    <p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Management</p>
                    <h2 class="mt-1 text-xl font-semibold text-slate-950">Administrators</h2>
                </div>
                <div v-if="view === 'table'" class="flex flex-wrap items-center gap-3">
                    <input v-model="search" @keyup.enter="applySearch" placeholder="Search admins..." class="rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    <label class="flex items-center gap-2 text-sm text-slate-600">
                        <input type="checkbox" v-model="activeOnly" @change="applySearch" /> Active only
                    </label>
                    <button @click="load" class="rounded-md border border-slate-300 px-3 py-2 text-sm text-slate-600 hover:bg-slate-50">Refresh</button>
                    <button @click="openCreate" class="rounded-md bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Add Admin</button>
                </div>
                <button v-else @click="cancelForm" class="rounded-md border border-slate-300 px-3 py-2 text-sm text-slate-600 hover:bg-slate-50">Back to list</button>
            </div>

            <!-- Create / Edit inline form -->
            <div v-if="view === 'create' || view === 'edit'" class="p-6">
                <h3 class="mb-4 text-sm font-semibold text-slate-950">{{ view === 'create' ? 'Add Admin' : 'Edit Admin' }}</h3>
                <div v-if="formError" class="mb-4 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{{ formError }}</div>
                <div class="grid gap-4 sm:grid-cols-3">
                    <div>
                        <label class="block text-xs font-medium text-slate-600">First name *</label>
                        <input v-model="form.firstName" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-slate-600">Last name</label>
                        <input v-model="form.lastName" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-slate-600">Email *</label>
                        <input v-model="form.email" type="email" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-slate-600">Mobile number *</label>
                        <input v-model="form.mobileNumber" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    </div>
                    <div v-if="view === 'create'">
                        <label class="block text-xs font-medium text-slate-600">Temporary password *</label>
                        <input v-model="form.password" type="password" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-slate-600">Type *</label>
                        <select v-model="form.adminType" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm">
                            <option value="A">Admin</option>
                            <option v-if="isSuperAdmin" value="S">Super Admin</option>
                        </select>
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-slate-600">Role</label>
                        <select v-model="form.roleId" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm">
                            <option value="">No role</option>
                            <option v-for="r in roles" :key="r.id" :value="r.id">{{ r.label }}</option>
                        </select>
                    </div>
                    <div v-if="view === 'edit'" class="flex items-end">
                        <label class="flex items-center gap-2 text-sm text-slate-600">
                            <input type="checkbox" v-model="form.isActive" /> Active
                        </label>
                    </div>
                </div>
                <div class="mt-6 flex gap-3">
                    <button @click="submitForm" :disabled="saving" class="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">
                        {{ saving ? 'Saving...' : (view === 'create' ? 'Create Admin' : 'Save changes') }}
                    </button>
                    <button @click="cancelForm" class="rounded-md border border-slate-300 px-4 py-2 text-sm text-slate-600">Cancel</button>
                </div>
            </div>

            <!-- Table -->
            <template v-else>
                <div class="overflow-x-auto">
                    <table class="min-w-full divide-y divide-slate-200 text-sm">
                        <thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
                            <tr>
                                <th class="px-5 py-3">Code</th>
                                <th class="px-5 py-3">Administrator</th>
                                <th class="px-5 py-3">Email</th>
                                <th class="px-5 py-3">Mobile</th>
                                <th class="px-5 py-3">Type</th>
                                <th class="px-5 py-3">Role</th>
                                <th class="px-5 py-3">Login URL</th>
                                <th class="px-5 py-3">Status</th>
                                <th class="px-5 py-3 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-slate-100">
                            <tr v-for="row in rows" :key="row.admin_id" class="hover:bg-slate-50">
                                <td class="px-5 py-3 text-slate-500">{{ row.admin_code || '-' }}</td>
                                <td class="px-5 py-3 font-medium text-slate-950">
                                    <Link :href="`/admin/admin-management/admins/${row.admin_id}`" class="hover:underline">{{ row.first_name }} {{ row.last_name }}</Link>
                                </td>
                                <td class="px-5 py-3 text-slate-600">{{ row.email }}</td>
                                <td class="px-5 py-3 text-slate-600">{{ row.mobile_number }}</td>
                                <td class="px-5 py-3 text-slate-600">{{ row.admin_type === 'S' ? 'Super Admin' : 'Admin' }}</td>
                                <td class="px-5 py-3 text-slate-600">{{ row.role_name || '-' }}</td>
                                <td class="px-5 py-3">
                                    <div class="flex items-center gap-2">
                                        <span class="max-w-[160px] truncate font-mono text-xs text-slate-500">{{ row.login_url }}</span>
                                        <button @click="copyLoginUrl(row)" class="text-xs text-indigo-600 hover:underline">{{ copiedId === row.admin_id ? 'Copied!' : 'Copy' }}</button>
                                    </div>
                                </td>
                                <td class="px-5 py-3">
                                    <button @click="row.is_active ? confirmDeactivate(row) : toggleActive(row)"
                                        class="rounded-full px-2 py-1 text-xs font-medium"
                                        :class="row.is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'">
                                        {{ row.is_active ? 'Active' : 'Inactive' }}
                                    </button>
                                </td>
                                <td class="px-5 py-3 text-right">
                                    <div class="flex justify-end gap-3 text-xs font-medium">
                                        <button @click="openEdit(row)" class="text-indigo-600 hover:underline">Edit</button>
                                        <button v-if="isSuperAdmin" @click="openPasswordModal(row)" class="text-slate-600 hover:underline">Password</button>
                                        <button @click="deleteRow(row)" class="text-red-600 hover:underline">Delete</button>
                                    </div>
                                </td>
                            </tr>
                            <tr v-if="!loading && rows.length === 0"><td colspan="9" class="px-5 py-10 text-center text-slate-400">No administrators found.</td></tr>
                            <tr v-if="loading"><td colspan="9" class="px-5 py-10 text-center text-slate-400">Loading...</td></tr>
                        </tbody>
                    </table>
                </div>

                <div class="flex items-center justify-between border-t border-slate-200 p-4 text-sm text-slate-500">
                    <span>{{ total }} total</span>
                    <div class="flex gap-2">
                        <button :disabled="page <= 1" @click="goToPage(page - 1)" class="rounded-md border border-slate-300 px-3 py-1 disabled:opacity-40">Prev</button>
                        <span>Page {{ page }} / {{ totalPages }}</span>
                        <button :disabled="page >= totalPages" @click="goToPage(page + 1)" class="rounded-md border border-slate-300 px-3 py-1 disabled:opacity-40">Next</button>
                    </div>
                </div>
            </template>
        </section>

        <!-- Deactivate confirmation modal -->
        <div v-if="deactivateTarget" class="fixed inset-0 z-40 flex items-center justify-center bg-black/40 p-4">
            <div class="w-full max-w-sm rounded-lg bg-white p-6 shadow-xl">
                <h3 class="text-base font-semibold text-slate-950">Deactivate Admin?</h3>
                <p class="mt-2 text-sm text-slate-500">This administration account will lose system access.</p>
                <div class="mt-6 flex justify-end gap-3">
                    <button @click="deactivateTarget = null" class="rounded-md border border-slate-300 px-4 py-2 text-sm">Cancel</button>
                    <button @click="doDeactivate" class="rounded-md bg-red-600 px-4 py-2 text-sm font-semibold text-white">Deactivate</button>
                </div>
            </div>
        </div>

        <!-- Password reset modal -->
        <div v-if="passwordTarget" class="fixed inset-0 z-40 flex items-center justify-center bg-black/40 p-4">
            <div class="w-full max-w-sm rounded-lg bg-white p-6 shadow-xl">
                <h3 class="text-base font-semibold text-slate-950">Reset Password</h3>
                <p class="mt-1 text-sm text-slate-500">{{ passwordTarget.first_name }} {{ passwordTarget.last_name }}</p>
                <div v-if="passwordError" class="mt-3 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{{ passwordError }}</div>
                <div class="mt-4 space-y-3">
                    <div>
                        <label class="block text-xs font-medium text-slate-600">New Password</label>
                        <input v-model="passwordForm.new" type="password" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    </div>
                    <div>
                        <label class="block text-xs font-medium text-slate-600">Confirm New Password</label>
                        <input v-model="passwordForm.confirm" type="password" class="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    </div>
                </div>
                <div class="mt-6 flex justify-end gap-3">
                    <button @click="passwordTarget = null" class="rounded-md border border-slate-300 px-4 py-2 text-sm">Cancel</button>
                    <button @click="submitPasswordReset" class="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Reset Password</button>
                </div>
            </div>
        </div>
    </AdminShell>
</template>

// tools/legacy-client-source/app/admin/admin-management/admins/page.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { Edit2, Trash2, BadgeAlert, Copy, Check, Key, X, Users } from "lucide-react";
import PaginatedTable, { Column, AvatarCell } from "@/app/admin/(components)/Table";
import { adminAPI } from "@/lib/api";
import { useAuthStore } from "@/store/auth.store";
import Modal from "@/components/modals/Modal";
import Input from '@/app/admin/(components)/Forms/Input';
import Toggle from '@/app/admin/(components)/Forms/Toggle';
import Select from '@/app/admin/(components)/Forms/Select';
import Form from '@/app/admin/(components)/Forms/Form';
import SuccessOverlay from "@/app/admin/(components)/Overlay/Successoverlay";
import FailedOverlay from "@/app/admin/(components)/Overlay/Failedoverlay";
import { ADMIN_TYPES } from "@/src/shared/constants/adminTypes";

export default function AdminsPage() {
  const router = useRouter();
  const user = useAuthStore((state) => state.user);
  const [data, setData] = useState<any[]>([]);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(false);
  const [sort, setSort] = useState<{ key: string | null; direction: string | null }>({ key: null, direction: null });
  const [, setSelectedIds] = useState<any[]>([]);

  // â"€â"€ Overlays â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [successOverlay, setSuccessOverlay] = useState(false);
  const [failedOverlay, setFailedOverlay] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  // â"€â"€ Deactivate Record â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [openDeactivateModal, setOpenDeactivateModal] = useState(false);
  const [toggleRecordid, setToggleRecordId] = useState<any>(null);

  // â"€â"€ Force Password Change â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [openPasswordModal, setOpenPasswordModal] = useState(false);
  const [passwordRecordId, setPasswordRecordId] = useState<any>(null);
  const [newPasswordForm, setNewPasswordForm] = useState({ new: "", confirm: "" });
  const [passwordError, setPasswordError] = useState("");
  const [passwordLoading, setPasswordLoading] = useState(false);

  const handlePasswordChangeIcon = (row: any) => {
    setPasswordRecordId(row.admin_id);
    setNewPasswordForm({ new: "", confirm: "" });
    setPasswordError("");
    setOpenPasswordModal(true);
  };

  const handleUpdatePassword = async (e: React.FormEvent) => {
    e.preventDefault();
    setPasswordError("");
    if (newPasswordForm.new !== newPasswordForm.confirm) {
      return setPasswordError("Passwords do not match");
    }
    if (newPasswordForm.new.length < 6) {
      return setPasswordError("Password must be at least 6 characters");
    }
    try {
      setPasswordLoading(true);
      await adminAPI.resetPassword({
        adminId: passwordRecordId,
        newPassword: newPasswordForm.new
      });
      setSuccessOverlay(true);
      setTimeout(() => {
        setSuccessOverlay(false);
        setOpenPasswordModal(false);
      }, 2000);
    } catch (err: any) {
      setPasswordError(err.message || "Failed to update password");
    } finally {
      setPasswordLoading(false);
    }
  };

  // â"€â"€ Create & Edit States â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [openCreateForm, setOpenCreateForm] = useState(false);
  const [openEditForm, setOpenEditForm] = useState(false);
  const [editRow, setEditRow] = useState<any>(null);
  const [createLoading, setCreateLoading] = useState(false);
  const [editLoading, setEditLoading] = useState(false);
  const [editForm, setEditForm] = useState({
    first_name: "",
    last_name: "",
    email: "",
    mobile_number: "",
    admin_type: "",
    is_active: false,
    role_id: "",
  });

  const [roles, setRoles] = useState<any[]>([]);
  const adminTypeOptions = [
    { id: ADMIN_TYPES.ADMIN, label: "Admin", value: ADMIN_TYPES.ADMIN },
    ...(user?.admin_type === ADMIN_TYPES.SUPER_ADMIN
      ? [{ id: ADMIN_TYPES.SUPER_ADMIN, label: "Super Admin", value: ADMIN_TYPES.SUPER_ADMIN }]
      : []),
  ];

  const [activeOnly, setActiveOnly] = useState(false);
  const [copiedId, setCopiedId] = useState<number | null>(null);

  const fetchAdmins = useCallback(async (overrides: any = {}) => {
    try {
      setLoading(true);
      const res = await adminAPI.getAdmins({
        page: overrides.page ?? page,
        limit: overrides.limit ?? limit,
        search: overrides.search ?? search,
        sortBy: overrides.sortKey ?? sort.key,
        sortDir: overrides.sortDir ?? sort.direction,
        isActive: (overrides.activeOnly ?? activeOnly) ? true : undefined,
      });
      if (res.status && res.data) {
        setData(res.data);
        setTotal(res.total);
        setPage(res.page);
      }
    } catch (err) {
      console.error("API Error:", err);
    } finally {
      setLoading(false);
    }
  }, [page, limit, search, sort, activeOnly]);

  useEffect(() => { fetchAdmins(); }, []);

  useEffect(() => {
    const fetchRoles = async () => {
      try {
        const res = await adminAPI.getRoleDropdown();
        if (res.status) setRoles(res.data);
      } catch (err) {
        console.error("Error fetching roles", err);
      }
    };
    fetchRoles();
  }, []);

  // â"€â"€ Toolbar & Filter Handlers â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleSearch = (value: string) => {
    setSearch(value);
    fetchAdmins({ search: value, page: 1 });
  };
  const handlePageChange = (p: number) => {
    setPage(p);
    fetchAdmins({ page: p });
  };
  const handleLimitChange = (l: number) => {
    setLimit(l);
    fetchAdmins({ limit: l, page: 1 });
  };
  const handleSort = ({ key, direction }: { key: string | null; direction: string | null }) => {
    setSort({ key, direction });
    fetchAdmins({ sortKey: key, sortDir: direction });
  };
  const handleActiveOnly = (value: boolean) => {
    setActiveOnly(value);
    fetchAdmins({ activeOnly: value, page: 1 });
  };

  // â"€â"€ Toggle Status â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleToggle = async (newValue: boolean, row: any) => {
    try {
      if (newValue) {
        // Just activate it via toggle API
        await adminAPI.deleteAdmin({ adminId: row.admin_id, isActive: true });
        fetchAdmins();
      } else {
        setToggleRecordId(row.admin_id);
        setOpenDeactivateModal(true);
      }
    } catch (err) {
      console.error("Toggle failed", err);
    }
  };

  const deactivateRecord = async () => {
    try {
      await adminAPI.deleteAdmin({ adminId: toggleRecordid, isActive: false });
      setOpenDeactivateModal(false);
      fetchAdmins();
    } catch (error) {
      console.error("Deactivate failed", error);
    }
  };

  // â"€â"€ Edit Logic â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleEdit = (row: any) => {
    setEditRow(row);
    setEditForm({
      first_name: row.first_name || "",
      last_name: row.last_name || "",
      email: row.email || "",
      mobile_number: row.mobile_number || "",
      admin_type: row.admin_type || "",
      is_active: row.is_active,
      role_id: row.role_id || "",
    });
    setOpenEditForm(true);
  };

  
  const handleUpdateSubmit = async (_formData: any, _values: any) => {
    setEditLoading(true);
    try {
      const payload = {
        adminId: editRow.admin_id,
        firstName: editForm.first_name,
        lastName: editForm.last_name,
        mobileNumber: editForm.mobile_number,
        email: editForm.email,
        adminType: editForm.admin_type,
        isActive: editForm.is_active,
        updatedBy: user?.admin_id,
        roleId: editForm.role_id,
      };

      // If a new password is typed, one could pass it, but standard update may ignore it unless specifically handled.

      const response = await adminAPI.updateAdmin(payload);
      if (response && response.status) {
        setSuccessOverlay(true);
        setTimeout(() => {
          setSuccessOverlay(false);
          setOpenEditForm(false);
          setEditRow(null);
          fetchAdmins();
        }, 2000);
      } else {
        setErrorMessage(response?.message || "Update failed");
        setFailedOverlay(true);
        setTimeout(() => setFailedOverlay(false), 3000);
      }
    } catch (err: any) {
      console.error("Update failed:", err);
      setErrorMessage(err.message || "An unexpected error occurred");
      setFailedOverlay(true);
      setTimeout(() => setFailedOverlay(false), 3000);
    } finally {
      setEditLoading(false);
    }
  };

  const handleDelete = async (row: any) => {
    if (!window.confirm(`Are you sure you want to delete admin "${row.first_name} ${row.last_name}"?`)) return;
    try {
      const res = await adminAPI.deleteAdmin({ adminId: row.admin_id, isActive: false });
      if (res.status) {
        setSuccessOverlay(true);
        fetchAdmins();
      } else {
        setErrorMessage(res.message || "Delete failed");
        setFailedOverlay(true);
      }
    } catch (err: any) {
      setErrorMessage(err.message || "An error occurred during deletion");
      setFailedOverlay(true);
    }
  };

  // â"€â"€ Bulk Actions â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleBulkDelete = async (ids: any[]) => {
    try {
      await Promise.all(ids.map(id => adminAPI.deleteAdmin({ adminId: id, isActive: false })));
      setSuccessOverlay(true);
      fetchAdmins();
    } catch (err) {
      setErrorMessage("Failed to delete some admins.");
      setFailedOverlay(true);
    }
  };

  const handleBulkActivate = async (ids: any[]) => {
    try {
      await Promise.all(ids.map(id => adminAPI.deleteAdmin({ adminId: id, isActive: true })));
      setSuccessOverlay(true);
      fetchAdmins();
    } catch (err) {
      setErrorMessage("Failed to activate some admins.");
      setFailedOverlay(true);
    }
  };

  const handleBulkDeactivate = async (ids: any[]) => {
    try {
      await Promise.all(ids.map(id => adminAPI.deleteAdmin({ adminId: id, isActive: false })));
      setSuccessOverlay(true);
      fetchAdmins();
    } catch (err) {
      setErrorMessage("Failed to deactivate some admins.");
      setFailedOverlay(true);
    }
  };

  return (
    <div className="space-y-6">

      <SuccessOverlay show={successOverlay} onFinish={() => setSuccessOverlay(false)} title="Success" subtitle="Admin profile saved." />
      <FailedOverlay 
        show={failedOverlay} 
        title="Failed" 
        subtitle={errorMessage || "Unable to save changes."} 
        onFinish={() => setFailedOverlay(false)} 
      />

      {/* â"€â"€ CREATE FORM â"€â"€ */}
      <Form
        showMe={openCreateForm}
        cols={3}
        card
        title="Add Administrator"
        subtitle="Create a new admin account"
        onSubmit={async (_formData: any, values: any) => {
          setCreateLoading(true);
          try {
            const payload = {
              firstName: values.first_name,
              lastName: values.last_name,
              email: values.email,
              mobileNumber: values.mobile_number,
              password: values.password,
              adminType: values.admin_type,
              createdBy: user?.admin_id,
              roleId: values.role_id,
            };
            const response = await adminAPI.register(payload);
            if (response && response.status) {
              setSuccessOverlay(true);
              setTimeout(() => {
                setSuccessOverlay(false);
                setOpenCreateForm(false);
                fetchAdmins();
              }, 2000);
            } else {
              setErrorMessage(response?.message || "Registration failed");
              setFailedOverlay(true);
              setTimeout(() => setFailedOverlay(false), 3000);
            }
          } catch (err: any) {
            console.error("Registration failed:", err);
            setErrorMessage(err.message || "An unexpected error occurred");
            setFailedOverlay(true);
            setTimeout(() => setFailedOverlay(false), 3000);
          } finally {
            setCreateLoading(false);
          }
        }}
        onReset={() => setOpenCreateForm(false)}
        submitLabel="Create Admin"
        showReset
        loading={createLoading}
      >
        <Input name="first_name" title="First Name" required />
        <Input name="last_name" title="Last Name" />
        <Input name="email" title="Email Address" type="email" required />
        <Input name="mobile_number" title="Mobile Number" required />
        <Input name="password" title="Temporary Password" type="password" required />
        <Select
          name="admin_type"
          title="Admin Type"
          required
          options={adminTypeOptions}
        />
        <Select
          name="role_id"
          title="Role"
          options={roles}
        />
        <Toggle title="Active" checked />
      </Form>

      {/* â"€â"€ EDIT FORM â"€â"€ */}
      {editRow && (
        <Form
          showMe={openEditForm}
          cols={3}
          card
          title="Edit Administrator"
          subtitle={`Editing: ${editRow.first_name} ${editRow.last_name || ''}`}
          onSubmit={handleUpdateSubmit}
          onReset={() => {
            setOpenEditForm(false);
            setEditRow(null);
          }}
          submitLabel="Save Changes"
          showReset
          loading={editLoading}
        >
          <Input
            name="first_name" title="First Name" required
            value={editForm.first_name} onChange={(e) => setEditForm(p => ({ ...p, first_name: e.target.value }))}
          />
          <Input
            name="last_name" title="Last Name"
            value={editForm.last_name} onChange={(e) => setEditForm(p => ({ ...p, last_name: e.target.value }))}
          />
          <Input
            name="email" title="Email Address" type="email" required
            value={editForm.email} onChange={(e) => setEditForm(p => ({ ...p, email: e.target.value }))}
          />
          <Input
            name="mobile_number" title="Mobile Number" required
            value={editForm.mobile_number} onChange={(e) => setEditForm(p => ({ ...p, mobile_number: e.target.value }))}
          />
          <Select
            name="admin_type" title="Admin Type"
            value={editForm.admin_type} onChange={(e) => setEditForm(p => ({ ...p, admin_type: e.target.value }))}
            options={adminTypeOptions}
          />
          <Select
            name="role_id" title="Role"
            value={editForm.role_id} 
            onChange={(e) => setEditForm(p => ({ ...p, role_id: e.target.value }))}
            options={roles}
          />
          <Toggle
            name="is_active" title="Active"
            checked={editForm.is_active} onChange={(v) => setEditForm(p => ({ ...p, is_active: v }))}
          />
        </Form>
      )}

      {/* â"€â"€ TABLE â"€â"€ */}
      <PaginatedTable
        showMe={!openCreateForm && !openEditForm}
        title="Administrators"
        badge="Management"
        subtitle={`${total} admins found`}
        data={data}
        total={total}
        loading={loading}
        page={page}
        limit={limit}
        onPageChange={handlePageChange}
        onLimitChange={handleLimitChange}
        onSort={handleSort}
        onSearch={handleSearch}
        searchValue={search}

        showSearch
        showFilter
        showAdd
        showRefresh
        addLabel="Add Admin"
        onAdd={() => setOpenCreateForm(true)}
        onRefresh={() => fetchAdmins()}
        rowKey="admin_id"
        onSelectionChange={setSelectedIds}
        enableSelection={true}

        filters={[
          {
            type: "toggle",
            label: "Active only",
            value: activeOnly,
            onChange: handleActiveOnly,
          },
        ]}
      >
        <Column header="SL" type="serial" />
        <Column header="Code" dataKey="admin_code" render={(v: any) => v ?? "-"} />
        <Column
          header="Administrator"
          dataKey="first_name" 
          type="avatar" 
          sortable 
          render={(_val, row) => (
            <button
              type="button"
              onClick={() => router.push(`/admin/admin-management/admins/${row.admin_id}`)}
              className="text-left cursor-pointer"
              title="View admin details"
            >
              <AvatarCell value={`${row.first_name} ${row.last_name}`} row={row} />
            </button>
          )}
        />
        <Column header="Email" dataKey="email" sortable />
        <Column header="Mobile" dataKey="mobile_number" />
        <Column
          header="Type"
          dataKey="admin_type"
          render={(val) => val === ADMIN_TYPES.SUPER_ADMIN ? "Super Admin" : val === ADMIN_TYPES.ADMIN ? "Admin" : val}
        />
        <Column header="Role" dataKey="role_name" />
        <Column
          header="Login URL"
          dataKey="login_url"
          render={(url, row) => (
            <div className="flex items-center gap-2">
              <div 
                className="px-2 py-1 rounded bg-[#f8fafc] border border-[#f1f5f9] text-[11px] font-mono text-[#53697e] truncate max-w-[120px]"
                title={url}
              >
                {url}
              </div>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(url);
                  setCopiedId(row.admin_id);
                  setTimeout(() => setCopiedId(null), 2000);
                }}
                className={`p-1.5 rounded-lg transition-all ${
                  copiedId === row.admin_id 
                  ? "bg-[#dcfce7] text-[#16a34a]" 
                  : "bg-[#f1f5f9] text-[#53697e] hover:bg-[#e2e8f0]"
                }`}
                title="Copy URL"
              >
                {copiedId === row.admin_id ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
              </button>
            </div>
          )}
        />
        <Column header="Status" dataKey="is_active" type="toggle" onToggle={handleToggle} />
        <Column
          header="Action"
          dataKey="_actions"
          type="actions"
          align="right"
          actions={[
            { label: "Edit", icon: Edit2, onClick: handleEdit },
            { 
              label: "Activate", 
              icon: Check, 
              onClick: (row) => handleToggle(true, row),
              onBulkClick: handleBulkActivate 
            },
            { 
              label: "Deactivate", 
              icon: X, 
              onClick: (row) => handleToggle(false, row),
              onBulkClick: handleBulkDeactivate 
            },
            { 
              label: "Delete", 
              icon: Trash2, 
              variant: "danger",
              onClick: (row) => handleDelete(row),
              onBulkClick: handleBulkDelete 
            },
            ...(user?.admin_type === ADMIN_TYPES.SUPER_ADMIN ? [{ label: "Password", icon: Key, onClick: handlePasswordChangeIcon }] : [])
          ]}
        />
      </PaginatedTable>

      {/* â"€â"€ DEACTIVATE MODAL â"€â"€ */}
      <Modal openModal={openDeactivateModal} setOpenModal={setOpenDeactivateModal}>
        <div className="p-2 bg-[#ffffff] rounded-2xl w-full max-w-sm mx-auto">
          <div className="relative mx-auto w-16 h-16 mb-5 flex items-center justify-center">
            <div className="absolute inset-0 rounded-2xl bg-[#fef2f2]" />
            <div className="relative w-10 h-10 rounded-xl bg-[#fef2f2] shadow flex items-center justify-center">
              <BadgeAlert className="w-5 h-5 text-[#ffffff]" />
            </div>
          </div>
          <h2 className="text-[16px] font-bold text-center">Deactivate Admin?</h2>
          <p className="mt-2 text-[13px] text-[#53697e] text-center mx-auto">
            This administration account will lose system access.
          </p>
          <div className="mt-6 flex gap-2.5">
            <button onClick={() => setOpenDeactivateModal(false)} className="flex-1 py-2.5 rounded-xl bg-[#f1f5f9] font-semibold text-[13px]">Cancel</button>
            <button onClick={deactivateRecord} className="flex-1 py-2.5 rounded-xl bg-[#fef2f2] text-[#ffffff] font-semibold text-[13px]">Deactivate</button>
          </div>
        </div>
      </Modal>

      {/* â"€â"€ CHANGE PASSWORD MODAL â"€â"€ */}
      <Modal openModal={openPasswordModal} setOpenModal={setOpenPasswordModal}>
        <form onSubmit={handleUpdatePassword} className="p-2 bg-[#ffffff] rounded-2xl w-full mx-auto">
          <div className="flex items-center justify-between mb-4 px-2">
            <div>
              <h2 className="text-[16px] font-bold text-[#0f172a]">Change Admin Password</h2>
              <p className="text-[11px] text-[#94a3b8]">Update this user's password securely</p>
            </div>
            <button type="button" onClick={() => setOpenPasswordModal(false)} className="text-[#94a3b8] hover:text-[#475569]">
              <X className="w-4 h-4" />
            </button>
          </div>
          <div className="space-y-3 px-2">
            <div>
              <label className="block text-[11px] font-medium text-[#53697e] mb-1">New Password</label>
              <input
                required
                type="password"
                value={newPasswordForm.new}
                onChange={(e) => setNewPasswordForm(p => ({ ...p, new: e.target.value }))}
                className="w-full px-3 py-2 text-[13px] bg-[#f8fafc] border border-[#e2e8f0] rounded-xl focus:bg-[#ffffff] transition-all outline-none focus:ring-2 focus:ring-[#dbeafe]"
                placeholder="â€¢â€¢â€¢â€¢â€¢â€¢â€¢â€¢"
              />
            </div>
            <div>
              <label className="block text-[11px] font-medium text-[#53697e] mb-1">Confirm New Password</label>
              <input
                required
                type="password"
                value={newPasswordForm.confirm}
                onChange={(e) => setNewPasswordForm(p => ({ ...p, confirm: e.target.value }))}
                className="w-full px-3 py-2 text-[13px] bg-[#f8fafc] border border-[#e2e8f0] rounded-xl focus:bg-[#ffffff] transition-all outline-none focus:ring-2 focus:ring-[#dbeafe]"
                placeholder="â€¢â€¢â€¢â€¢â€¢â€¢â€¢â€¢"
              />
            </div>
            {passwordError && <p className="text-[11px] text-[#7b5757] font-medium px-1">{passwordError}</p>}
          </div>
          <div className="mt-6 flex gap-2.5 px-2">
            <button type="button" onClick={() => setOpenPasswordModal(false)} className="flex-1 py-2.5 rounded-xl text-[13px] font-semibold text-[#475569] bg-[#f1f5f9] hover:bg-[#e2e8f0] transition-colors">Cancel</button>
            <button disabled={passwordLoading} type="submit" className="flex-1 py-2.5 rounded-xl text-[13px] font-semibold text-[#ffffff] bg-[#2563eb] hover:bg-[#1d4ed8] shadow-sm shadow-[#dbeafe] disabled:opacity-50 transition-all">
              {passwordLoading ? "Updating..." : "Update Password"}
            </button>
          </div>
        </form>
      </Modal>

    </div>
  );
}
