// resources/js/Pages/Admin/AdminManagement/Menus/Index.vue
<script setup>
import { ref, computed, onMounted } from 'vue';
import AdminShell from '@/Layouts/AdminShell.vue';
import { adminApi } from '@/lib/apiClient';
import MenuFormDrawer from './MenuFormDrawer.vue';

const rows = ref([]);
const total = ref(0);
const page = ref(1);
const limit = ref(10);
const search = ref('');
const activeOnly = ref(false);
const loading = ref(true);
const parents = ref([]);
const groups = ref([]);

const drawerOpen = ref(false);
const drawerMode = ref('create');
const drawerMenu = ref(null);
const saving = ref(false);
const deactivateTarget = ref(null);

const typeBadge = { P: { label: 'Section', class: 'bg-blue-100 text-blue-700' }, C: { label: 'Sub-menu', class: 'bg-purple-100 text-purple-700' }, I: { label: 'Link', class: 'bg-pink-100 text-pink-700' } };

async function load() {
    loading.value = true;
    const res = await adminApi.paginatedMenu({
        page: page.value, limit: limit.value, search: search.value || undefined,
        isActive: activeOnly.value ? true : undefined,
    });
    if (res?.status !== false) {
        rows.value = res.data || [];
        total.value = res.total ?? 0;
    }
    loading.value = false;
}

async function loadLookups() {
    const [parentsRes, groupsRes] = await Promise.all([adminApi.getMenuParent(), adminApi.getMenuGroup()]);
    if (parentsRes?.status !== false) parents.value = parentsRes.parents || [];
    if (groupsRes?.status !== false) groups.value = groupsRes.groups || [];
}

onMounted(() => {
    load();
    loadLookups();
});

function applySearch() {
    page.value = 1;
    load();
}

function goToPage(p) {
    page.value = p;
    load();
}

const totalPages = computed(() => Math.max(1, Math.ceil(total.value / limit.value)));

function openCreate() {
    drawerMode.value = 'create';
    drawerMenu.value = null;
    drawerOpen.value = true;
}

function openEdit(row) {
    drawerMode.value = 'edit';
    drawerMenu.value = row;
    drawerOpen.value = true;
}

async function handleSubmit(payload) {
    saving.value = true;
    let res;
    if (drawerMode.value === 'edit') {
        res = await adminApi.updateMenu({
            menuId: drawerMenu.value.menu_id, menuName: payload.menu_name, menuPath: payload.menu_path,
            menuIcon: payload.menu_icon, isActive: payload.is_active,
        });
    } else {
        res = await adminApi.createMenu({
            menuName: payload.menu_name, menuPath: payload.menu_path, menuIcon: payload.menu_icon,
            menuParentId: payload.menu_type === 'C' ? payload.menu_parent_id : null,
            menuGroupId: payload.menu_group_id, menuGroup: payload.menu_group, menuType: payload.menu_type,
        });
        await loadLookups();
    }
    saving.value = false;
    if (res?.status === false) {
        window.alert(res.message || 'Something went wrong.');
        return;
    }
    drawerOpen.value = false;
    load();
}

async function toggleActive(row) {
    const next = !row.is_active;
    row.is_active = next;
    const res = next ? await adminApi.activateMenu({ menuId: row.menu_id }) : null;
    if (!next) {
        deactivateTarget.value = row;
        row.is_active = true; // revert until confirmed
        return;
    }
    if (res?.status === false) row.is_active = !next;
}

async function doDeactivate() {
    const row = deactivateTarget.value;
    deactivateTarget.value = null;
    if (!row) return;
    row.is_active = false;
    const res = await adminApi.deactivateMenu({ menuId: row.menu_id });
    if (res?.status === false) row.is_active = true;
}

async function deleteRow(row, index) {
    if (!window.confirm(`Delete menu "${row.menu_name}"?`)) return;
    rows.value.splice(index, 1);
    const res = await adminApi.deleteMenu({ menuId: row.menu_id });
    if (res?.status === false) {
        load();
        return;
    }
    if (rows.value.length === 0 && page.value > 1) {
        page.value -= 1;
    }
    load();
}
</script>

<template>
    <AdminShell title="Admin's Menus" source="client/app/admin/admin-management/menus/page.tsx">
        <section class="rounded-lg border border-slate-200 bg-white shadow-sm">
            <div class="flex flex-col gap-3 border-b border-slate-200 p-5 lg:flex-row lg:items-center lg:justify-between">
                <div>
                    <p class="text-xs font-semibold uppercase tracking-wide text-indigo-600">Admin</p>
                    <h2 class="mt-1 text-xl font-semibold text-slate-950">Admin's Menus</h2>
                </div>
                <div class="flex flex-wrap items-center gap-3">
                    <input v-model="search" @keyup.enter="applySearch" placeholder="Search menus..." class="rounded-md border border-slate-300 px-3 py-2 text-sm" />
                    <label class="flex items-center gap-2 text-sm text-slate-600">
                        <input type="checkbox" v-model="activeOnly" @change="applySearch" /> Active only
                    </label>
                    <button @click="load" class="rounded-md border border-slate-300 px-3 py-2 text-sm text-slate-600 hover:bg-slate-50">Refresh</button>
                    <button @click="openCreate" class="rounded-md bg-slate-900 px-3 py-2 text-sm font-semibold text-white">Add Menu</button>
                </div>
            </div>

            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-slate-200 text-sm">
                    <thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500">
                        <tr>
                            <th class="px-5 py-3">Menu Name</th>
                            <th class="px-5 py-3">Path</th>
                            <th class="px-5 py-3">Group</th>
                            <th class="px-5 py-3">Type</th>
                            <th class="px-5 py-3">Status</th>
                            <th class="px-5 py-3 text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-100">
                        <tr v-for="(row, idx) in rows" :key="row.menu_id" class="hover:bg-slate-50">
                            <td class="px-5 py-3 font-medium text-slate-950">{{ row.menu_name }}</td>
                            <td class="px-5 py-3 font-mono text-xs text-slate-500">{{ row.menu_path }}</td>
                            <td class="px-5 py-3 text-slate-600">{{ row.menu_group }}</td>
                            <td class="px-5 py-3">
                                <span class="rounded-full px-2 py-1 text-xs font-medium" :class="typeBadge[row.menu_type]?.class || 'bg-slate-100 text-slate-600'">
                                    {{ typeBadge[row.menu_type]?.label || row.menu_type }}
                                </span>
                            </td>
                            <td class="px-5 py-3">
                                <button @click="toggleActive(row)" class="rounded-full px-2 py-1 text-xs font-medium" :class="row.is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'">
                                    {{ row.is_active ? 'Active' : 'Inactive' }}
                                </button>
                            </td>
                            <td class="px-5 py-3 text-right">
                                <div class="flex justify-end gap-3 text-xs font-medium">
                                    <button @click="openEdit(row)" class="text-indigo-600 hover:underline">Edit</button>
                                    <button @click="deleteRow(row, idx)" class="text-red-600 hover:underline">Delete</button>
                                </div>
                            </td>
                        </tr>
                        <tr v-if="!loading && rows.length === 0"><td colspan="6" class="px-5 py-10 text-center text-slate-400">No menus found. Click "Add Menu" to get started.</td></tr>
                        <tr v-if="loading"><td colspan="6" class="px-5 py-10 text-center text-slate-400">Loading...</td></tr>
                    </tbody>
                </table>
            </div>

            <div class="flex items-center justify-between border-t border-slate-200 p-4 text-sm text-slate-500">
                <span>{{ total }} total</span>
                <div class="flex gap-2">
                    <button :disabled="page <= 1" @click="goToPage(page - 1)" class="rounded-md border border-slate-300 px-3 py-1 disabled:opacity-40">Prev</button>
                    <span>Page {{ page }} / {{ totalPages }}</span>
                    <button :disabled="page >= totalPages" @click="goToPage(page + 1)" class="rounded-md border border-slate-300 px-3 py-1 disabled:opacity-40">Next</button>
                </div>
            </div>
        </section>

        <MenuFormDrawer
            :open="drawerOpen"
            :mode="drawerMode"
            :menu="drawerMenu"
            :parents="parents"
            :groups="groups"
            :saving="saving"
            @close="drawerOpen = false"
            @submit="handleSubmit"
        />

        <div v-if="deactivateTarget" class="fixed inset-0 z-40 flex items-center justify-center bg-black/40 p-4">
            <div class="w-full max-w-sm rounded-lg bg-white p-6 shadow-xl">
                <h3 class="text-base font-semibold text-slate-950">Are you sure?</h3>
                <p class="mt-2 text-sm text-slate-500">It will disappear from the sidebar once deactivated.</p>
                <div class="mt-6 flex justify-end gap-3">
                    <button @click="deactivateTarget = null" class="rounded-md border border-slate-300 px-4 py-2 text-sm">Cancel</button>
                    <button @click="doDeactivate" class="rounded-md bg-red-600 px-4 py-2 text-sm font-semibold text-white">Deactivate</button>
                </div>
            </div>
        </div>
    </AdminShell>
</template>

// tools/legacy-client-source/app/admin/admin-management/menus/page.tsx
"use client";

import { useState, useEffect, useCallback } from "react";
import { Edit2, Trash2, BadgeAlert, Check, X, LayoutTemplate } from "lucide-react";
import PaginatedTable, { Column } from "@/app/admin/(components)/Table/Paginatedtable";
import { adminAPI } from "@/lib/api";
import { useAuthStore } from "@/store/auth.store";
import Modal from "@/components/modals/Modal";
import MenuFormDrawer, { type MenuFormValues } from "./MenuFormDrawer";

type MenuQueryOverrides = {
  page?: number;
  limit?: number;
  search?: string;
  sortKey?: string | null;
  sortDir?: string | null;
  type?: string;
  fromDate?: string;
  toDate?: string;
  activeOnly?: boolean;
};

import SuccessOverlay from "@/app/admin/(components)/Overlay/Successoverlay";
import FailedOverlay from "@/app/admin/(components)/Overlay/Failedoverlay";

export default function AdminMenus() {
  const user = useAuthStore((state) => state.user);
  const [menus, setMenus] = useState<any[]>([]);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(false);
  const [sort, setSort] = useState<{ key: string | null; direction: string | null }>({ key: null, direction: null });

  // â"€â"€ Overlay States â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [successOverlay, setSuccessOverlay] = useState(false);
  const [failedOverlay, setFailedOverlay] = useState(false);

  // â"€â"€ Options States â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [menuParent, setMenuParent] = useState<{ id: number; label: string }[]>([]);
  const [menuGroup, setMenuGroup] = useState<{ id: number; label: string }[]>([]);

  // â"€â"€ Deactivate Record state â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [openDeactivateModal, setOpenDeactivateModal] = useState(false);
  const [toggleRecordid, setToggleRecordId] = useState<any>(null);

  // â"€â"€ Create Form state â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [formOpen, setFormOpen] = useState(false);
  const [formMode, setFormMode] = useState<"create" | "edit">("create");
  const [editRow, setEditRow] = useState<any>(null);
  const [formLoading, setFormLoading] = useState(false);
  const [formInitial, setFormInitial] = useState<Partial<MenuFormValues> | null>(null);

  // â"€â"€ Filter state â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const [typeFilter, setTypeFilter] = useState("");
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [activeOnly, setActiveOnly] = useState(false);

  // â"€â"€ Core fetch â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const fetchMenus = useCallback(async (overrides: MenuQueryOverrides = {}) => {
    try {
      setLoading(true);
      const res = await adminAPI.paginatedMenu({
        page: overrides.page ?? page,
        limit: overrides.limit ?? limit,
        search: overrides.search ?? search,
        sortBy: overrides.sortKey ?? sort.key,
        sortDir: overrides.sortDir ?? sort.direction,
        type: overrides.type ?? typeFilter,
        fromDate: overrides.fromDate ?? fromDate,
        toDate: overrides.toDate ?? toDate,
        // ðŸ"¥ FIX: only send isActive:true if activeOnly is true. 
        // Backend filtering for isActive:false was returning 0 results.
        isActive: (overrides.activeOnly ?? activeOnly) ? true : undefined,
      });
      if (res.status) {
        setMenus(res.data);
        setTotal(res.total);
        setPage(res.page);
      }
    } catch (err) {
      console.error("API Error:", err);
    } finally {
      setLoading(false);
    }
  }, [page, limit, search, sort, typeFilter, fromDate, toDate, activeOnly]);

  // Initial load
  useEffect(() => { fetchMenus(); }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    const fetchData = async () => {
      try {
        const menuParents = await adminAPI.getMenuParent();
        const menuGroups = await adminAPI.getMenuGroup();
        setMenuParent(menuParents.parents);
        setMenuGroup(menuGroups.groups);
      } catch (err) {
        console.error("Error fetching menu parents:", err);
      }
    };
    fetchData();
  }, []);

  // â"€â"€ Toolbar handlers â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleSearch = (value: string) => {
    setSearch(value);
    setPage(1);
    fetchMenus({ search: value, page: 1 });
  };

  const handlePageChange = (p: number) => {
    setPage(p);
    fetchMenus({ page: p });
  };

  const handleLimitChange = (l: number) => {
    setLimit(l);
    setPage(1);
    fetchMenus({ limit: l, page: 1 });
  };

  const handleSort = ({ key, direction }: { key: string | null; direction: string | null }) => {
    setSort({ key, direction });
    fetchMenus({ sortKey: key, sortDir: direction });
  };

  const [selectedIds, setSelectedIds] = useState<any[]>([]);

  // â"€â"€ Handlers for bulk actions â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleBulkDelete = async (ids: any[]) => {
    try {
      await Promise.all(ids.map(id => adminAPI.deleteMenu({ menuId: id })));
      setSuccessOverlay(true);
      setTimeout(() => {
        setSuccessOverlay(false);
        fetchMenus();
      }, 2000);
    } catch (err) {
      setFailedOverlay(true);
      setTimeout(() => setFailedOverlay(false), 3000);
    }
  };

  const handleBulkActivate = async (ids: any[]) => {
    try {
      const response = await adminAPI.bulkActivateMenu({ menuIds: ids });
      if (response.status) {
        setSuccessOverlay(true);
        setTimeout(() => {
          setSuccessOverlay(false);
          fetchMenus();
        }, 2000);
      }
    } catch (err) {
      setFailedOverlay(true);
      setTimeout(() => setFailedOverlay(false), 3000);
    }
  };

  const handleBulkDeactivate = async (ids: any[]) => {
    try {
      const response = await adminAPI.bulkDeactivateMenu({ menuIds: ids });
      if (response.status) {
        setSuccessOverlay(true);
        setTimeout(() => {
          setSuccessOverlay(false);
          fetchMenus();
        }, 2000);
      }
    } catch (err) {
      setFailedOverlay(true);
      setTimeout(() => setFailedOverlay(false), 3000);
    }
  };

  // â"€â"€ Filter handlers â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleTypeFilter = (value: string) => {
    setTypeFilter(value);
    setPage(1);
    fetchMenus({ type: value, page: 1 });
  };

  const handleFromDate = (value: string) => {
    setFromDate(value);
    setPage(1);
    fetchMenus({ fromDate: value, page: 1 });
  };

  const handleToDate = (value: string) => {
    setToDate(value);
    setPage(1);
    fetchMenus({ toDate: value, page: 1 });
  };

  const handleActiveOnly = (value: boolean) => {
    setActiveOnly(value);
    setPage(1);
    fetchMenus({ activeOnly: value, page: 1 });
  };

  // â"€â"€ Toggle (is_active) â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleToggle = async (newValue: boolean, row: any) => {
    try {
      if (newValue) {
        const response = await adminAPI.activateMenu({ menuId: row.menu_id });
        if (response.status) {
          setSuccessOverlay(true);
          setTimeout(() => {
            setSuccessOverlay(false);
            fetchMenus();
          }, 2000);
        }
      } else {
        setToggleRecordId(row.menu_id);
        setOpenDeactivateModal(true);
      }
    } catch (err) {
      console.error("Toggle failed, rolling back:", err);
      setFailedOverlay(true);
      setTimeout(() => setFailedOverlay(false), 3000);
      setMenus((prev) =>
        prev.map((m) =>
          m.menu_id === row.menu_id ? { ...m, is_active: !newValue } : m
        )
      );
    }
  };

  const deactivateRecord = async () => {
    try {
      const response = await adminAPI.deactivateMenu({ menuId: toggleRecordid });
      if (response.status) {
        setOpenDeactivateModal(false);
        setSuccessOverlay(true);
        setTimeout(() => {
          setSuccessOverlay(false);
          fetchMenus();
        }, 2000);
      }
    } catch (error) {
      console.error("Toggle failed, rolling back:", error);
      setFailedOverlay(true);
      setTimeout(() => setFailedOverlay(false), 3000);
    }
  };

  // â"€â"€ Edit handler - opens the Edit form pre-populated with row data â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const openCreate = () => {
    setFormMode("create");
    setEditRow(null);
    setFormInitial(null);
    setFormOpen(true);
  };

  const handleEdit = (row: any) => {
    setEditRow(row);
    setFormMode("edit");
    setFormInitial({
      menu_name: row.menu_name || "",
      menu_path: row.menu_path || "",
      menu_icon: row.menu_icon || "LayoutGrid",
      placement: (String(row.menu_type || "I").toUpperCase() as MenuFormValues["placement"]),
      is_active: row.is_active !== false,
    });
    setFormOpen(true);
  };

  const closeForm = () => {
    setFormOpen(false);
    setEditRow(null);
    setFormInitial(null);
  };

  const handleFormSubmit = async (values: MenuFormValues) => {
    setFormLoading(true);
    try {
      if (formMode === "create") {
        const groupName =
          values.new_group_name ||
          menuGroup.find((g) => String(g.id) === String(values.menu_group_id))?.label ||
          "";
        const response = await adminAPI.createMenu({
          menuName: values.menu_name,
          menuPath: values.menu_path,
          menuIcon: values.menu_icon || "LayoutGrid",
          menuParentId: values.placement === "C" ? values.menu_parent_id || null : null,
          menuGroupId: values.menu_group_id || null,
          menuGroup: groupName,
          menuType: values.placement,
          createdBy: user?.admin_id?.toString() || "system",
        });
        if (response.status) {
          setSuccessOverlay(true);
          setTimeout(() => {
            setSuccessOverlay(false);
            closeForm();
            fetchMenus();
            adminAPI.getMenuGroup().then((r) => r.groups && setMenuGroup(r.groups));
          }, 2000);
        } else {
          setFailedOverlay(true);
        }
      } else if (editRow) {
        const response = await adminAPI.updateMenu({
          menuId: editRow.menu_id,
          menuName: values.menu_name,
          menuPath: values.menu_path,
          menuIcon: values.menu_icon || "LayoutGrid",
          isActive: values.is_active,
          updatedBy: user?.admin_id?.toString() || "system",
        });
        if (response.status) {
          setSuccessOverlay(true);
          setTimeout(() => {
            setSuccessOverlay(false);
            closeForm();
            fetchMenus();
          }, 2000);
        } else {
          setFailedOverlay(true);
        }
      }
    } catch (err) {
      console.error(err);
      setFailedOverlay(true);
    } finally {
      setFormLoading(false);
    }
  };

  // â"€â"€ Delete handler â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€
  const handleDelete = async (row: any) => {
    const confirmed = window.confirm(
      `Delete menu "${row.menu_name}"? This action cannot be undone.`
    );
    if (!confirmed) return;

    setMenus((prev) => prev.filter((m) => m.menu_id !== row.menu_id));
    setTotal((prev) => prev - 1);

    try {
      const resp = await adminAPI.deleteMenu({ menuId: row.menu_id });
      if (resp.status) {
        setSuccessOverlay(true);
        setTimeout(() => {
          setSuccessOverlay(false);
          const remainingOnPage = menus.length - 1;
          if (remainingOnPage === 0 && page > 1) {
            handlePageChange(page - 1);
          } else {
            fetchMenus();
          }
        }, 2000);
      } else {
        setFailedOverlay(true);
        setTimeout(() => setFailedOverlay(false), 3000);
        fetchMenus();
      }
    } catch (err) {
      console.error("Delete failed, rolling back:", err);
      setFailedOverlay(true);
      setTimeout(() => setFailedOverlay(false), 3000);
      fetchMenus();
    }
  };

  // â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€

  return (
    <div className="space-y-6">


      {/* â"€â"€ Overlays â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€ */}
      <SuccessOverlay
        show={successOverlay}
        onFinish={() => setSuccessOverlay(false)}
        title="Saved successfully!"
        subtitle="Menu has been updated."
      />
      <FailedOverlay
        show={failedOverlay}
        title="Action failed"
        subtitle="Something went wrong. Please try again."
        onFinish={() => setFailedOverlay(false)}
      />

      <MenuFormDrawer
        open={formOpen}
        mode={formMode}
        initial={formInitial}
        parentOptions={menuParent}
        groupOptions={menuGroup}
        loading={formLoading}
        onClose={closeForm}
        onSubmit={handleFormSubmit}
      />

      {/* â"€â"€ Paginated Table â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€ */}
      <PaginatedTable
        showMe={!formOpen}
        data={menus}
        total={total}
        loading={loading}
        page={page}
        limit={limit}
        onPageChange={handlePageChange}
        onLimitChange={handleLimitChange}
        onSort={handleSort}
        onSearch={handleSearch}
        searchValue={search}

        title="Admin's Menus"
        badge="Admin"
        subtitle={`${total} records found`}

        showSearch
        showFilter
        showAdd
        showRefresh
        addLabel="Add Menu"
        onAdd={openCreate}
        onRefresh={() => fetchMenus()}
        onExport={() => console.log("export")}

        rowKey="menu_id"
        onSelectionChange={setSelectedIds}
        enableSelection={true}
        searchPlaceholder="Search menus..."
        emptyMessage="No menus found. Click 'Add Menu' to get started."

        filters={[
          {
            type: "dropdown",
            value: typeFilter,
            onChange: handleTypeFilter,
            placeholder: "All Types",
            options: [
              { label: "Section heading", value: "p" },
              { label: "Sub-menu", value: "c" },
              { label: "Regular link", value: "i" },
            ],
          },
          {
            type: "daterange",
            fromValue: fromDate,
            toValue: toDate,
            onFromChange: handleFromDate,
            onToChange: handleToDate,
          },
          {
            type: "toggle",
            label: "Active only",
            value: activeOnly,
            onChange: handleActiveOnly,
          },
        ]}
      >
        {/* â"€â"€ Column definitions â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€ */}
        <Column header="SL" type="serial" />

        <Column dataKey="menu_name" header="Menu Name" sortable />

        <Column dataKey="menu_path" header="Path" type="link" />

        <Column dataKey="menu_group" header="Group" type="chips" sortable />

        <Column
          dataKey="menu_type"
          header="Type"
          render={(value) => {
            const key = String(value).toLowerCase();
            const map: Record<string, { label: string; color: string }> = {
              p: { label: "Section", color: "blue" },
              c: { label: "Sub-menu", color: "purple" },
              i: { label: "Link", color: "pink" },
            };
            const cfg = map[key];
            const styles: Record<string, { badge: string; dot: string }> = {
              blue: { badge: "bg-[#eff6ff]   text-[#1d4ed8]   ring-[#bfdbfe]", dot: "bg-[#eff6ff]" },
              purple: { badge: "bg-[#faf5ff] text-[#7e22ce] ring-[#e9d5ff]", dot: "bg-[#faf5ff]" },
              pink: { badge: "bg-[#fdf2f8]   text-[#be185d]   ring-[#fbcfe8]", dot: "bg-[#fdf2f8]" },
              slate: { badge: "bg-[#f1f5f9] text-[#475569]  ring-[#e2e8f0]", dot: "bg-[#94a3b8]" },
            };
            const { badge } = styles[cfg?.color ?? 'slate'];
            return (
              <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-medium ${badge}`}>
                {cfg?.label ?? value}
              </span>
            );
          }}
        />

        <Column
          dataKey="is_active"
          header="Status"
          type="toggle"
          onToggle={handleToggle}
        />

        <Column
          dataKey="_actions"
          header="Action"
          type="actions"
          align="right"
          actions={[
            {
              label: "Edit",
              icon: Edit2,
              variant: "default",
              onClick: (row: any) => handleEdit(row),
            },
            {
              label: "Activate",
              icon: Check,
              variant: "default",
              onClick: (row: any) => handleToggle(true, row),
              onBulkClick: handleBulkActivate,
            },
            {
              label: "Deactivate",
              icon: X,
              variant: "default",
              onClick: (row: any) => handleToggle(false, row),
              onBulkClick: handleBulkDeactivate,
            },
            {
              label: "Delete",
              icon: Trash2,
              variant: "danger",
              onClick: (row: any) => handleDelete(row),
              onBulkClick: handleBulkDelete,
            },
          ]}
        />
      </PaginatedTable>

      {/* â"€â"€ Deactivate Alert Modal â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€â"€ */}
      <Modal openModal={openDeactivateModal} setOpenModal={setOpenDeactivateModal}>
        <div className="p-2 bg-[#ffffff] rounded-2xl w-full max-w-sm mx-auto">
          <div className="relative mx-auto w-16 h-16 mb-5 flex items-center justify-center">
            <div className="absolute inset-0 rounded-2xl bg-[#fef2f2]" />
            <div className="absolute inset-0 rounded-2xl bg-[#fee2e2] blur-lg opacity-50 animate-pulse" />
            <div className="relative w-10 h-10 rounded-xl bg-[#fef2f2] shadow-md shadow-[#fecaca] flex items-center justify-center">
              <BadgeAlert className="w-5 h-5 text-[#ffffff]" strokeWidth={2.5} />
            </div>
          </div>
          <h2 className="text-[16px] font-bold text-[#0f172a] text-center leading-tight">
            Are you sure?
          </h2>
          <p className="mt-2 text-[13px] text-[#94a3b8] text-center leading-relaxed mx-auto">
            Are you sure you want to deactivate this menu? It will disappear from
            the sidebar once deactivated.
          </p>
          <div className="mt-6 flex gap-2.5">
            <button
              onClick={() => setOpenDeactivateModal(false)}
              className="flex-1 py-2.5 rounded-xl text-[13px] font-semibold
                text-[#475569] bg-[#f1f5f9] hover:bg-[#e2e8f0] transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={deactivateRecord}
              className="flex-1 py-2.5 rounded-xl text-[13px] font-semibold
                text-[#ffffff] bg-[#fef2f2] hover:bg-[#dc2626]
                shadow-sm shadow-[#fee2e2] active:scale-[0.98] transition-all"
            >
              Deactivate
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
